CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS FRAUD_DETECTION;

USE DATABASE FRAUD_DETECTION;

CREATE SCHEMA IF NOT EXISTS RAW;