USE DATABASE FRAUD_DETECTION;
USE SCHEMA RAW;

CREATE OR REPLACE STREAM RAW_TRANSACTION_STREAM
ON TABLE RAW_TRANSACTIONS
APPEND_ONLY = TRUE;

COMMENT ON STREAM RAW_TRANSACTION_STREAM IS
'CDC stream tracking newly inserted transaction events';